# Generated by Django 3.2.9 on 2022-01-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_initial'),
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_choice', to='carrier.traineeposition', verbose_name='First Choice'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice', to='carrier.traineeposition', verbose_name='Second Choice'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choice', to='carrier.traineeposition', verbose_name='Third Choice'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_choice', to='carrier.traineeposition', verbose_name='Fourth Choice'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_choice', to='carrier.traineeposition', verbose_name='Fifth Choice'),
        ),
    ]
