# Generated by Django 3.2.9 on 2022-01-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_initial'),
        ('internships_app', '0001_initial'),
        ('applicant', '0003_auto_20220129_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internships_app.undergraduatestudent'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='trainee_position_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_choice', to='carrier.traineeposition', verbose_name='Fourth Choice'),
        ),
    ]
