version: "3.7"
services:
  db:
    image: postgres
    container_name: internships_db
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin
    volumes:
      - ../data/db:/var/lib/postgresql/data;
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: internships_web
    #command: /run/django_init.sh
    #command: python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./InternshipsTracker/.env
    ports:
      - 8001:8001
    volumes:
      - ./InternshipsTracker:/appinternships
      - ./logs:/var/log
    depends_on:
      - db
    command: /usr/local/bin/gunicorn InternshipsTracker.wsgi:application -w 2 -b :8001 --reload
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./code/static:/static
    depends_on:
      - web  