# Generated by Django 3.2.9 on 2022-01-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineeposition',
            name='application_period',
        ),
    ]
