# Generated by Django 3.2.9 on 2022-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_remove_traineeposition_application_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='finalized',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=1),
        ),
    ]
