# Generated by Django 3.2.9 on 2022-01-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0002_alter_undergraduatestudent_register_date'),
        ('carrier', '0005_alter_assignment_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierconsent',
            name='assignement_upon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.assignment'),
        ),
        migrations.AlterField(
            model_name='carrierconsent',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.carrier'),
        ),
    ]
