# Generated by Django 3.2.9 on 2022-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0006_auto_20220130_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntershipReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics')], max_length=3, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
    ]
