# Generated by Django 3.2.9 on 2022-02-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0007_intershipreportperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='finalized',
            new_name='assignment_status',
        ),
    ]
