# Generated by Django 3.2.9 on 2022-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_rename_finalized_assignment_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='assignmentperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='carrierassignmentperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='intershipreportperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3, unique=True),
        ),
    ]
