# Generated by Django 3.2.9 on 2021-12-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ThesisApp', '0001_initial'),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.undergraduatestudent')),
                ('trainee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.traineeposition')),
            ],
        ),
    ]
