# Generated by Django 3.2.9 on 2021-12-18 23:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ThesisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('complementary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierAssignmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TraineePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1500)),
                ('application_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.applicationperiod')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consent', models.BooleanField()),
                ('assignement_upon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrier.assignment')),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierAssesement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(max_length=1000)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('assignement_upon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrier.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.assignmentperiod'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.supervisor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='trainee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.undergraduatestudent'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='trainee_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.traineeposition'),
        ),
    ]
