# Generated by Django 3.2.9 on 2022-01-28 03:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0001_initial'),
        ('internships_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(max_length=1500)),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.supervisor')),
                ('trainee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.traineeposition')),
            ],
        ),
    ]
