# Generated by Django 3.2.9 on 2022-01-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternshipsApp', '0001_initial'),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationperiod',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='assignmentperiod',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='carrierassignmentperiod',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='traineeposition',
            name='carrier',
        ),
        migrations.AddField(
            model_name='applicationperiod',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InternshipsApp.carrier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentperiod',
            name='carrier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='InternshipsApp.carrier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrierassignmentperiod',
            name='carrier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='InternshipsApp.carrier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineeposition',
            name='carrier_assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrierassignmentperiod'),
            preserve_default=False,
        ),
    ]
