# Generated by Django 3.2.9 on 2022-01-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InternshipsApp', '0001_initial'),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternshipsApp.undergraduatestudent')),
                ('trainee_position_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_choice', to='carrier.traineeposition', unique=True, verbose_name='First Choice')),
                ('trainee_position_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice', to='carrier.traineeposition', unique=True, verbose_name='Second Choice')),
                ('trainee_position_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choice', to='carrier.traineeposition', unique=True, verbose_name='Third Choice')),
                ('trainee_position_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_choice', to='carrier.traineeposition', unique=True, verbose_name='Fourth Choice')),
                ('trainee_position_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_choice', to='carrier.traineeposition', unique=True, verbose_name='Fifth Choice')),
            ],
        ),
    ]
