# Generated by Django 3.2.9 on 2022-01-28 03:54

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=100)),
                ('street_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
            ],
            options={
                'unique_together': {('country', 'city', 'street_name', 'street_no', 'postal_code')},
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('department', models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics')], max_length=3)),
                ('full_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.address', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateStudent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('tel_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('register_number', models.CharField(max_length=10, unique=True)),
                ('register_date', models.DateField()),
                ('department', models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics')], max_length=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.address', unique=True)),
            ],
            options={
                'verbose_name': 'Undergraduate Student',
                'verbose_name_plural': 'Undergraduate Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('tel_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('register_number', models.CharField(max_length=10, unique=True)),
                ('register_date', models.DateField()),
                ('department', models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics')], max_length=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.address', unique=True)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarrierNode',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('tel_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('department', models.CharField(max_length=150)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.address', unique=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.carrier')),
            ],
            options={
                'verbose_name': 'Carrier Node',
                'verbose_name_plural': 'Carrier Nodes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
