# Generated by Django 3.2.9 on 2022-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
