# Generated by Django 3.2.9 on 2022-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='secratarian',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary'), ('NON', 'Νone')], max_length=3),
        ),
    ]
