# Generated by Django 3.2.9 on 2022-04-07 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='carriernode',
            name='department',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Ζ ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='carriernode',
            name='father_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='carriernode',
            name='mother_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='secratarian',
            name='alias_identifier',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Ζ ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='secratarian',
            name='father_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='secratarian',
            name='mother_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='father_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mother_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='register_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Ζ ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='father_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='mother_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='register_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Ζ ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
