# Generated by Django 3.2.9 on 2022-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0002_auto_20220407_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='department_1',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='department_2',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='department_3',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='department_4',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3),
        ),
    ]
