# Generated by Django 3.2.9 on 2022-02-09 22:23

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('internships_app', '0002_alter_undergraduatestudent_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3),
        ),
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3),
        ),
        migrations.CreateModel(
            name='Secratarian',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('department', models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('ALL', 'Secreatary')], max_length=3)),
                ('alias_identifier', models.CharField(max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internships_app.address')),
            ],
            options={
                'verbose_name': 'Secretarian',
                'verbose_name_plural': 'Secretarians',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
