# Generated by Django 3.2.9 on 2022-05-04 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships_app', '0004_auto_20220504_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undergraduatestudent',
            name='register_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Ζ ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together={('register_number', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='undergraduatestudent',
            unique_together={('register_number', 'department')},
        ),
    ]
